// examples/vue/VideoPlayer.vue
<template>
  <div 
    ref="container" 
    class="player-wrapper"
    :style="{ width: '100%', aspectRatio: '16/9', background: '#000' }"
  >
    <video 
      ref="video" 
      :poster="poster" 
      crossorigin="anonymous" 
    />
  </div>
</template>

<script setup>
import { ref, onMounted, onBeforeUnmount, watch } from 'vue';
import { Player, createControls, createGestures, createHlsPlugin } from 'agnostic-player';
import 'agnostic-player/styles/player.css';

const props = defineProps({
  src: { type: String, required: true },
  poster: { type: String, default: '' },
  autoplay: { type: Boolean, default: false }
});

const container = ref(null);
const video = ref(null);
let player = null;

onMounted(async () => {
  if (!video.value || !container.value) return;

  // Initialize Player
  player = new Player({
    media: video.value,
    container: container.value,
    autoplay: props.autoplay
  });

  // Add Plugins
  await player.usePlugin(createControls());
  await player.usePlugin(createGestures());
  await player.usePlugin(createHlsPlugin());

  // Set Source
  player.setSource(props.src);
});

onBeforeUnmount(() => {
  if (player) {
    player.destroy();
  }
});

// Watch for source changes
watch(() => props.src, (newSrc) => {
  if (player) {
    player.setSource(newSrc);
  }
});
</script>

<style scoped>
/* Any component-specific styles */
</style>

// examples/preact/VideoPlayer.tsx
import { h } from 'preact';
import { useEffect, useRef } from 'preact/hooks';
import { Player, createControls, createGestures, createHlsPlugin } from 'agnostic-player';
import 'agnostic-player/styles/player.css';

interface PlayerProps {
  src: string;
  poster?: string;
  autoplay?: boolean;
}

export const VideoPlayer = ({ src, poster, autoplay }: PlayerProps) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const playerRef = useRef<Player | null>(null);

  useEffect(() => {
    if (!videoRef.current || !containerRef.current) return;

    // Initialize Player
    const player = new Player({
      media: videoRef.current,
      container: containerRef.current,
      autoplay: autoplay || false
    });

    // Add Plugins
    const setupPlugins = async () => {
        await player.usePlugin(createControls());
        await player.usePlugin(createGestures());
        await player.usePlugin(createHlsPlugin());
        
        // Set Source
        player.setSource(src);
    }
    
    setupPlugins();

    playerRef.current = player;

    return () => {
      // Cleanup
      player.destroy();
    };
  }, [src, autoplay]);

  return (
    <div 
      ref={containerRef} 
      className="player-wrapper"
      style={{ width: '100%', aspectRatio: '16/9', background: '#000' }}
    >
      <video 
        ref={videoRef} 
        poster={poster} 
        crossorigin="anonymous" 
      />
    </div>
  );
};

// Usage Example:
// <VideoPlayer src="https://example.com/stream.m3u8" />
